In [1]:
import numpy as np


In [2]:
new=np.arange(10)
new=new.astype(float)
new

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [3]:
type(np.nan)

float

In [4]:
new[4]=np.nan
new

array([ 0.,  1.,  2.,  3., nan,  5.,  6.,  7.,  8.,  9.])

In [10]:
arr_rand=np.array([8,9,7,5,6,12,4,3,6,4])
print("Array:",arr_rand)

Array: [ 8  9  7  5  6 12  4  3  6  4]


In [11]:
arr_rand[arr_rand>5]

array([ 8,  9,  7,  6, 12,  6])

In [12]:
np.where(arr_rand>5)

(array([0, 1, 2, 4, 5, 8]),)

In [13]:
np.where(arr_rand >5,'GS','L5')

array(['GS', 'GS', 'GS', 'L5', 'GS', 'GS', 'L5', 'L5', 'GS', 'L5'],
      dtype='<U2')

In [14]:
np.where(arr_rand<10,'l10',np.where(arr_rand<20,'l20','g20'))

array(['l10', 'l10', 'l10', 'l10', 'l10', 'l20', 'l10', 'l10', 'l10',
       'l10'], dtype='<U3')

In [15]:
data=r"C:\Users\91879\Downloads\Datasets\DATASETS ML\tmdb_5000_movies.csv"
data

'C:\\Users\\91879\\Downloads\\Datasets\\DATASETS ML\\tmdb_5000_movies.csv'

In [18]:
a=np.array([0,1])

In [19]:
b=np.array([1,1])

In [20]:
np.hstack([a,b])

array([0, 1, 1, 1])

In [23]:
np.c_[a,b]

array([[0, 1],
       [1, 1]])

In [27]:
arr=np.random.randint(0,10,size=[8,5])
arr

array([[3, 5, 2, 5, 3],
       [1, 3, 5, 2, 3],
       [0, 2, 0, 5, 0],
       [2, 3, 2, 4, 7],
       [3, 2, 4, 5, 3],
       [6, 0, 9, 2, 9],
       [2, 1, 9, 8, 6],
       [1, 6, 6, 0, 5]], dtype=int32)

In [28]:
np.mean(arr,axis=1)
        

array([3.6, 2.8, 1.4, 3.6, 3.4, 5.2, 5.2, 3.6])

In [32]:
np.sort(arr,axis=0)

array([[0, 0, 0, 0, 0],
       [1, 1, 2, 2, 3],
       [1, 2, 2, 2, 3],
       [2, 2, 4, 4, 3],
       [2, 3, 5, 5, 5],
       [3, 3, 6, 5, 6],
       [3, 5, 9, 5, 7],
       [6, 6, 9, 8, 9]], dtype=int32)

In [34]:
sorted_index_column1=arr[:,0].argsort()
sorted_index_column1

array([2, 1, 7, 3, 6, 0, 4, 5])

In [35]:
arr[sorted_index_column1]

array([[0, 2, 0, 5, 0],
       [1, 3, 5, 2, 3],
       [1, 6, 6, 0, 5],
       [2, 3, 2, 4, 7],
       [2, 1, 9, 8, 6],
       [3, 5, 2, 5, 3],
       [3, 2, 4, 5, 3],
       [6, 0, 9, 2, 9]], dtype=int32)

In [33]:
arr[:,0]

array([3, 1, 0, 2, 3, 6, 2, 1], dtype=int32)

In [36]:
arr[sorted_index_column1,::-1]

array([[0, 5, 0, 2, 0],
       [3, 2, 5, 3, 1],
       [5, 0, 6, 6, 1],
       [7, 4, 2, 3, 2],
       [6, 8, 9, 1, 2],
       [3, 5, 2, 5, 3],
       [3, 5, 4, 2, 3],
       [9, 2, 9, 0, 6]], dtype=int32)

In [38]:
lexsorted_index=np.lexsort((arr[:,1],arr[:,2]))
lexsorted_index

array([2, 3, 0, 4, 1, 7, 5, 6])

In [39]:
arr[lexsorted_index]

array([[0, 2, 0, 5, 0],
       [2, 3, 2, 4, 7],
       [3, 5, 2, 5, 3],
       [3, 2, 4, 5, 3],
       [1, 3, 5, 2, 3],
       [1, 6, 6, 0, 5],
       [6, 0, 9, 2, 9],
       [2, 1, 9, 8, 6]], dtype=int32)